#pragma once
#include <Arduino.h>

const char PROVISIONING_HTML[] PROGMEM = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#1f7964"><title>Water Level Sensor Setup</title>
<style>
:root{font:16px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif;color:#18342c;background:#f3f7f4}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:18px;background:radial-gradient(circle at 85% 0,#d8eee6,transparent 36%),#f3f7f4}.card{width:min(520px,100%);padding:30px;border:1px solid #d9e4de;border-radius:24px;background:#fff;box-shadow:0 24px 70px #234c3e1c}.mark{display:grid;place-items:center;width:48px;height:48px;border-radius:15px;background:#1f7964;color:#fff;font-size:25px}h1{margin:20px 0 7px;font-size:2rem;letter-spacing:-.04em}p{color:#65766f;margin:0 0 22px}.step{display:none}.step.active{display:block}label{display:grid;gap:7px;margin:14px 0;font-weight:700;font-size:.85rem}input,select,button{width:100%;padding:13px 14px;border:1px solid #cbd8d1;border-radius:11px;background:#fbfcfb;font:inherit}button{margin-top:10px;border-color:#1f7964;background:#1f7964;color:#fff;font-weight:800;cursor:pointer}button.secondary{background:#eef4f1;color:#18342c;border-color:#d5e0da}button:disabled{opacity:.5}.network{display:flex;align-items:center;justify-content:space-between;margin:8px 0;padding:13px;border:1px solid #dce5e0;border-radius:12px;cursor:pointer}.network:hover{border-color:#1f7964;background:#f5faf8}.network small{color:#73827c}.message{padding:13px;border-radius:11px;background:#edf5f1;color:#375f52;font-size:.88rem}.message.error{background:#fff0ed;color:#963d34}.spinner{width:42px;height:42px;margin:25px auto;border:4px solid #dce9e4;border-top-color:#1f7964;border-radius:50%;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.result{text-align:center}.address{display:block;margin:10px 0;padding:12px;border-radius:10px;background:#eef4f1;font-weight:800;word-break:break-all}.row{display:grid;grid-template-columns:1fr auto;gap:8px}.row button{width:auto;margin:0}.hint{font-size:.78rem;color:#778780}.device{font-family:ui-monospace,monospace;color:#1f7964}
</style></head><body><main class="card"><div class="mark">◒</div>
<section id="welcome" class="step active"><h1>Set up your sensor</h1><p>Connect this water-level sensor to the same local 2.4 GHz Wi-Fi network as your phone or computer.</p><div class="message">This temporary setup network has no internet. It closes automatically after the sensor joins your normal Wi-Fi.</div><p class="device" id="deviceId">WaterLevel</p><button onclick="showNetworks()">Set up Wi-Fi</button></section>
<section id="networks" class="step"><h1>Choose a network</h1><p>Only 2.4 GHz networks are supported.</p><div id="networkList"><div class="message">Scanning nearby networks…</div></div><button class="secondary" onclick="scanNetworks()">Scan again</button><button class="secondary" onclick="chooseNetwork('')">Enter network manually</button></section>
<section id="credentials" class="step"><h1>Connect to Wi-Fi</h1><p>Enter the details for the network the sensor should use.</p><form id="wifiForm"><label>Network name (SSID)<input id="ssid" maxlength="32" required></label><label>Password<div class="row"><input id="password" type="password" maxlength="64"><button type="button" class="secondary" onclick="togglePassword()">Show</button></div></label><label>Sensor name<input id="hostname" value="water-level" maxlength="32" pattern="[a-z0-9-]+" required></label><p class="hint">The password is write-only and will not be displayed again.</p><button id="connectButton" type="submit">Connect</button><button type="button" class="secondary" onclick="setStep('networks')">Back</button></form></section>
<section id="progress" class="step result"><div class="spinner"></div><h1>Connecting…</h1><p id="progressText">Saving your settings and contacting the network.</p></section>
<section id="success" class="step result"><h1>Sensor is ready</h1><p id="reconnectText">The temporary setup network will close shortly. Reconnect this device to your normal Wi-Fi, then open either address:</p><span class="address" id="hostAddress"></span><span class="address" id="ipAddress"></span><p class="hint">Sign in once with the deployment bootstrap credential, then create permanent administrator and maintenance-network passwords.</p><button onclick="openDashboard()">Open dashboard after reconnecting</button></section>
<section id="failure" class="step result"><h1>Could not connect</h1><p id="failureText">Check the password and try again.</p><button onclick="setStep('credentials')">Check settings</button><button class="secondary" onclick="showNetworks()">Choose another network</button></section>
</main><script>
const steps=['welcome','networks','credentials','progress','success','failure'];let result={};
function setStep(id){steps.forEach(x=>document.getElementById(x).classList.toggle('active',x===id))}
async function loadInfo(){try{const r=await fetch('/api/setup/status');const j=await r.json();document.getElementById('deviceId').textContent=j.apSsid||'WaterLevel Sensor';if(j.hostname)document.getElementById('hostname').value=j.hostname}catch{}}
async function showNetworks(){setStep('networks');await scanNetworks()}
async function scanNetworks(){const list=document.getElementById('networkList');list.innerHTML='<div class="message">Scanning nearby networks…</div>';try{const r=await fetch('/api/setup/networks');const j=await r.json();list.innerHTML='';if(!j.networks.length)list.innerHTML='<div class="message error">No networks found. Move closer to the router or enter the name manually.</div>';j.networks.forEach(n=>{const el=document.createElement('div');el.className='network';el.innerHTML='<strong></strong><small></small>';el.querySelector('strong').textContent=n.ssid;el.querySelector('small').textContent=(n.secured?'🔒 ':'')+(n.rssi>-55?'Strong':n.rssi>-72?'Good':'Weak');el.onclick=()=>chooseNetwork(n.ssid);list.appendChild(el)})}catch{list.innerHTML='<div class="message error">Scan failed. Try again.</div>'}}
function chooseNetwork(ssid){document.getElementById('ssid').value=ssid;setStep('credentials');document.getElementById(ssid?'password':'ssid').focus()}
function togglePassword(){const i=document.getElementById('password');i.type=i.type==='password'?'text':'password'}
document.getElementById('wifiForm').onsubmit=async e=>{e.preventDefault();const body={ssid:document.getElementById('ssid').value.trim(),password:document.getElementById('password').value,hostname:document.getElementById('hostname').value.trim().toLowerCase()};setStep('progress');try{const r=await fetch('/api/setup/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json()).message||'Invalid settings');poll()}catch(e){document.getElementById('failureText').textContent=e.message;setStep('failure')}};
async function poll(){try{const r=await fetch('/api/setup/status');result=await r.json();document.getElementById('progressText').textContent=result.message||'Connecting…';if(result.state==='connected'){document.getElementById('hostAddress').textContent='http://'+result.hostname+'.local';document.getElementById('ipAddress').textContent='http://'+result.ipAddress;const seconds=result.setupAccessPointShutdownSeconds||0;const network=result.normalNetworkSsid?' “'+result.normalNetworkSsid+'”':'';document.getElementById('reconnectText').textContent='The temporary setup network will close'+(seconds?' in about '+seconds+' seconds':' shortly')+'. Reconnect this device to your normal Wi-Fi'+network+', then open either address:';setStep('success');return}if(result.state==='failed'){document.getElementById('failureText').textContent=result.message||'Check the password and try again.';setStep('failure');return}}catch{}setTimeout(poll,1000)}
function openDashboard(){location.href='http://'+(result.hostname||'water-level')+'.local'}loadInfo();
</script></body></html>)HTML";
